CC=gcc
CFLAGS=-Wall -std=c99

.PHONY: all clean

all: day1 day2 day3 day4 day5

day1: 
	$(CC) $(CFLAGS) day1.c -o day1.e

day2: 
	$(CC) $(CFLAGS) day2.c -o day2.e	

day3: 
	$(CC) $(CFLAGS) day3.c -o day3.e	

day4: 
	$(CC) $(CFLAGS) day4.c -o day4.e	

day5: 
	$(CC) $(CFLAGS) day5.c -o day5.e	

clean:
	rm -f  *.e